-- Liste der zu filternden Wörter
filterWords = {
    "icecrown",
    "rcu",
    "sylvanas",
    "chromies",
    "dawn",
    "iced",
    "iced out",
    "infestus",
    "nova community",
    "oblivion",
    "paradise",
    "picsou",
    "shrouded",
    "smoothboost",
    "sylvanas",
    "virtualgravity",
    "chromies",
    "exclusives angebot",
    "anal",
    "armor stack",
    "armorstack",
    "boosted",
    "boosting",
    "boosts",
    "booste",
    "boost",
    "chromies",
    "dawn",
    "fod community",
    "garona",
    "+0",
    "+1",
    "+2",
    "+3",
    "+4",
    "+5",
    "+6",
    "+7",
    "+8",
    "+9",
    "+10",
    "+11",
    "+12",
    "+13",
    "+14",
    "+15",
    "+ 0",
    "+ 1",
    "+ 2",
    "+ 3",
    "+ 4",
    "+ 5",
    "+ 6",
    "+ 7",
    "+ 8",
    "+ 9",
    "+ 10",
    "+ 11",
    "+ 12",
    "+ 13",
    "+ 14",
    "+ 15",
    "m+0",
    "m+1",
    "m+2",
    "m+3",
    "m+4",
    "m+5",
    "m+6",
    "m+7",
    "m+8",
    "m+9",
    "m+10",
    "m+11",
    "m+12",
    "m+13",
    "m+14",
    "m+15",
    "m+ 0",
    "m+ 1",
    "m+ 2",
    "m+ 3",
    "m+ 4",
    "m+ 5",
    "m+ 6",
    "m+ 7",
    "m+ 8",
    "m+ 9",
    "m+ 10",
    "m+ 11",
    "m+ 12",
    "m+ 13",
    "m+ 14",
    "m+ 15",
    "m+20",
    "m+keys",
    "m+ keys",
    "nova",
    "oblivion",
    "rape",
    "smoothboost",
    "sylvanas community",
    "twitch",
    "verkauft",
    "vip",
    "vip run",
    "wts heroisch",
    "wts key",
    "wts sod",
    "tooaddicted",
    "angelsoforgrimmar",
    "wir verkaufen",
    "verkaufen mythic",
    "verkaufen m+",
    "einzelne keys",
    "pepega",
    "intime garantie",
    "void",
    "v o i d",
    "loot trading",
    "armorstack",
    "rüstungsstack",
    "server time",
    "nur gold",
    "TWILIGHT",
    "DEVICE",
    "OXYGEN THIEFS",
    "WTS Sanctum of Domination",
    "WTS [Sanctum of Domination]",
    "now 250k",
    "wowvendor",
    "TitaniumBay",
    "wts raid heroic",
    "trade-raid.com",
    "bietet m+",
    "twitch",
    "Verkaufen",
    "Chance",
    "JETZT",
    "320k",
    "170k",
    "Chance",
    "270k",
    "4x20",
    "HC",
    "Lootshare",
    "Verkaufen JETZT",
    "Chance auf",
    "Beide ",
    "keystone master",
    "BESTEN PREISE",
    "Wir bieten alle an"
}
